# Generated by Django 3.0.3 on 2020-06-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('keyDate', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('FullDate', models.DateField()),
                ('dayOfWeek', models.CharField(max_length=10)),
                ('dayInWeek', models.IntegerField()),
                ('isHoliday', models.BooleanField()),
                ('isWeekend', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DimEmployee',
            fields=[
                ('empId', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timeId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.DimEmployee')),
                ('keyDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.DimDate')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.TimeTable')),
            ],
        ),
    ]
