# Generated by Django 3.0.3 on 2020-06-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='category',
            field=models.CharField(max_length=25),
        ),
    ]
